### ISSUE TITLE
execute und escaping und so

### ISSUE THREAD

**Issue by jjwedemyer** [GoeDev/BioDatenbanken#1]
https://github.com/GoeDev/BioDatenbanken/blob/ad8808482c9477b7e437be848c58f300e3a5d262/database.py#L51-55

https://docs.python.org/2/library/sqlite3.html

nubs

**Comment by LemiSt24** [comment]
Siehe https://github.com/GoeDev/BioDatenbanken/commit/c3b63acc7732352db447bd3df69c3c15dc413ca7

**Comment by jjwedemyer** [comment]
das meinte ich zwar gar nicht aber auch gut  :D 

> # Never do this -- insecure!
> symbol = 'RHAT'
> c.execute("SELECT * FROM stocks WHERE symbol = '%s'" % symbol)
> 
> # Do this instead
> t = ('RHAT',)
> c.execute('SELECT * FROM stocks WHERE symbol=?', t)
> print c.fetchone()
> 
> # Larger example that inserts many records at a time
> purchases = [('2006-03-28', 'BUY', 'IBM', 1000, 45.00),
>              ('2006-04-05', 'BUY', 'MSFT', 1000, 72.00),
>              ('2006-04-06', 'SELL', 'IBM', 500, 53.00),
>             ]
> c.executemany('INSERT INTO stocks VALUES (?,?,?,?,?)', purchases)
>
